"""TTS service.
   Priority: ElevenLabs → Cloudflare TTS.
   Returns MP3 bytes; designed to stream straight from the API.
"""
from __future__ import annotations
import os
import httpx
import logging

log = logging.getLogger("tts")


async def synth(text: str, *, voice: str | None, timeout: float) -> tuple[bytes, str]:
    # 1) ElevenLabs
    el_key = os.environ.get("ELEVENLABS_API_KEY")
    if el_key:
        try:
            v = voice or "Rachel"
            async with httpx.AsyncClient(timeout=timeout) as cx:
                r = await cx.post(
                    f"https://api.elevenlabs.io/v1/text-to-speech/{v}",
                    headers={"xi-api-key": el_key, "accept": "audio/mpeg"},
                    json={"text": text, "model_id": "eleven_turbo_v2_5",
                          "voice_settings": {"stability": 0.5, "similarity_boost": 0.7}},
                )
                r.raise_for_status()
                return r.content, "elevenlabs"
        except Exception as e:
            log.warning(f"elevenlabs.fail {type(e).__name__}")

    # 2) Cloudflare TTS (browser Speech Synthesis is the *client* fallback;
    #    the server still returns a small WAV generated by CF if available).
    acct = os.environ.get("CLOUDFLARE_ACCOUNT_ID")
    tok = os.environ.get("CLOUDFLARE_API_TOKEN")
    if acct and tok:
        try:
            async with httpx.AsyncClient(timeout=timeout) as cx:
                r = await cx.post(
                    f"https://api.cloudflare.com/client/v4/accounts/{acct}/ai/tts",
                    headers={"authorization": f"Bearer {tok}"},
                    json={"text": text, "voice": "en-US-Standard-A"},
                )
                r.raise_for_status()
                return r.content, "cloudflare"
        except Exception as e:
            log.warning(f"cloudflare.tts.fail {type(e).__name__}")

    # 3) Minimal silent WAV (1s) — never raw 500.
    from .silence import silent_wav
    return silent_wav(sec=1), "silent"
